kind: pipeline
type: docker
name: internal-gateway

steps:
  - name: compile-internal-gateway
    image: mcr.microsoft.com/dotnet/sdk:6.0
    pull: if-not-exists
    commands:
      - cd host/InternalGateway
      - dotnet publish -c Release -o ./publish /p:UseAppHost=false

  - name: deploy-internal-gateway
    image: drillster/drone-rsync:latest
    pull: if-not-exists
    settings:
      hosts:
        - 192.168.110.101
      port: 22
      user:
        from_secret: ssh_name
      key:
        from_secret: ssh_key
      secrets: [ ssh_key ]
      source: host/InternalGateway/publish
      target: /data/TravelEnjoyment/internal-gateway
      delete: true
      script:
       - cd /data/TravelEnjoyment/internal-gateway/publish
       - source handle.sh

#公共网关管道
---
kind: pipeline
type: docker
name: public-gateway

steps:
  - name: compile-public-gateway
    image: mcr.microsoft.com/dotnet/sdk:6.0
    pull: if-not-exists
    commands:
      - cd host/PublicGateway
      - dotnet publish -c Release -o ./publish /p:UseAppHost=false

  - name: deploy-public-gateway
    image: drillster/drone-rsync:latest
    pull: if-not-exists
    settings:
      hosts:
        - 192.168.110.101
      port: 22
      user:
        from_secret: ssh_name
      key:
        from_secret: ssh_key
      secrets: [ ssh_key ]
      source: host/PublicGateway/publish
      target: /data/TravelEnjoyment/public-gateway
      delete: true
      script:
       - cd /data/TravelEnjoyment/public-gateway/publish
       - source handle.sh

#钉钉通知管道
---
kind: pipeline
type: docker
name: notice

steps:
  - name: notice-dingtalk
    image: lddsb/drone-dingtalk-message:latest
    pull: if-not-exists
    settings:
      debug: true
      token: 
        from_secret: dingtalk_token
      type: markdown
      tpl: ./messagetpl/dingtalk-msg.tpl

trigger:
  status:
    - success

depends_on:
  - internal-gateway
  - public-gateway