kind: pipeline
type: docker
name: .NET6

steps:
  - name: compile-internal-gateway
    image: mcr.microsoft.com/dotnet/sdk:6.0
    pull: if-not-exists
    commands:
      - cd host/InternalGateway
      - dotnet restore
      - dotnet build
      - dotnet publish -c Release -o ./bin/publish
  
  - name: build-docker-image
    image: plugins/docker
    settings:
      username: admin
      password:
        from_secret: harbor_secret_key
      repo: 192.168.110.101:90/library/internal-gateway
      registry: 192.168.110.101:90
      auto_tag: true
      dockerfile: host/InternalGateway/Dockerfile