kind: pipeline
type: docker
name: .NET6

steps:
  - name: compile-internal-gateway
    image: mcr.microsoft.com/dotnet/sdk:6.0
    pull: if-not-exists
    commands:
      - cd host/InternalGateway
      - dotnet restore
      - dotnet build -c Release
      # - dotnet publish -c Release -o ./bin/publish
  
  - name: build-docker-image
    image: plugins/docker
    settings:
      username: 
        from_secret: username
      password:
        from_secret: password
      repo: registry.cn-hangzhou.aliyuncs.com/rours/internal-gateway
      registry: registry.cn-hangzhou.aliyuncs.com
      tags: latest
      insecure: true
      dockerfile: host/InternalGateway/Dockerfile