kind: pipeline
type: docker
name: .NET6

steps:
  - name: compile-internal-gateway
    image: mcr.microsoft.com/dotnet/sdk:6.0
    pull: if-not-exists
    commands:
      - cd host/InternalGateway
      - dotnet publish -c Release -o ./publish /p:UseAppHost=false

  - name: deploy-internal-gateway
    image: drillster/drone-rsync:latest
    pull: if-not-exists
    settings:
      hosts:
        - 192.168.110.101
      port: 22
      user:
        from_secret: ssh_name
      key:
        from_secret: ssh_key
      secrets: [ ssh_key ]
      source: host/InternalGateway/publish
      target: /data/TravelEnjoyment/internal-gateway
      delete: true
      script:
       - cd /data/TravelEnjoyment/internal-gateway/publish
       - docker stop te-internal-gateway
       - docker rm te-internal-gateway
       - docker images | grep internal-gateway | awk '{print $3}' | xargs docker rmi -f
       - docker build -t internal-gateway:latest .
       - docker tag internal-gateway 192.168.110.101:90/travel-enjoyment/internal-gateway:latest
       - docker push 192.168.110.101:90/travel-enjoyment/internal-gateway:latest
       - docker run -d --name te-internal-gateway -p 59600:59600 internal-gateway



#钉钉通知管道
---
kind: pipeline
type: docker
name: notice

steps:
  - name: notice-dingtalk
    image: lddsb/drone-dingtalk-message:latest
    pull: if-not-exists
    settings:
      debug: true
      token: 
        from_secret: dingtalk_token
      type: markdown
      tpl: ./messagetpl/dingtalk-msg.tpl

trigger:
  status:
    - success

depends_on:
  - .NET6